# Generated by Django 4.2.4 on 2023-10-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('image_path', models.CharField(default='assets/default_image.jpg', max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('configuration', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('variants', models.JSONField(default=list)),
                ('car_colors', models.JSONField(default=list)),
            ],
        ),
    ]
